const MongoClient = require('mongodb').MongoClient;

const uri = "mongodb+srv://usuarioprueba:ImMo9NtNl1cdbWeu@cluster0.iuzwtmv.mongodb.net/?retryWrites=true&w=majority";

const client = new MongoClient(uri, { useNewUrlParser: true });
client.connect(err => {
    if(err) throw err;
    const collection = client.db("datosPrueba").collection("prueba1");
    collection.insertMany(dentistas, function(err, res) {
    console.log("Datos insertados");
    client.close();
    });
});

const dentistas =   
[
    {
      idSucursal: '83771112',
      rut: '214',
      nombre: 'Lynne Kris',
      apellido: 'Shields',
      telefono: '60-722575-028604-9',
      email: 'Katelynn5@yahoo.com',
      direccion: '0244',
      nombreusuario: 'Laverne MacGyver IV',
      password: 'loeypxzm',
      agendaOnline: '8',
      ciudad: 'Jackson',
      duracionConsulta: '3'
    },
    {
      idSucursal: '53379398',
      rut: '903',
      nombre: 'Aubrey Block',
      apellido: 'Stehr',
      telefono: '41-758720-881521-0',
      email: 'Geraldine.Vandervort98@yahoo.com',
      direccion: '014',
      nombreusuario: 'Ms. Rosa Green',
      password: 'oluwmwvg',
      agendaOnline: '6',
      ciudad: 'Cathedral City',
      duracionConsulta: '3'
    },
    {
      idSucursal: '74345370',
      rut: '122',
      nombre: 'Miss Lena Lang',
      apellido: 'Heidenreich',
      telefono: '42-083046-285947-3',
      email: 'Haleigh.Cormier76@gmail.com',
      direccion: '8967',
      nombreusuario: 'Israel Hegmann',
      password: 'lxvbajkl',
      agendaOnline: '1',
      ciudad: 'South Valley',
      duracionConsulta: '9'
    },
    {
      idSucursal: '38363816',
      rut: '258',
      nombre: 'Willard Paucek',
      apellido: 'Kutch',
      telefono: '17-391529-680417-2',
      email: 'Green71@gmail.com',
      direccion: '63339',
      nombreusuario: 'Charlotte Schinner',
      password: 'tkjdkgyo',
      agendaOnline: '5',
      ciudad: 'Weymouth Town',
      duracionConsulta: '8'
    },
    {
      idSucursal: '16709412',
      rut: '106',
      nombre: 'Lynn Murray',
      apellido: 'Goyette',
      telefono: '59-874833-263052-6',
      email: 'Bartholome64@yahoo.com',
      direccion: '7229',
      nombreusuario: 'Adam Yost',
      password: 'aoeamysc',
      agendaOnline: '9',
      ciudad: 'Chicago',
      duracionConsulta: '0'
    },
    {
      idSucursal: '51240351',
      rut: '971',
      nombre: 'Freda Champlin DVM',
      apellido: 'Haley',
      telefono: '61-483091-259846-1',
      email: 'Reid53@gmail.com',
      direccion: '888',
      nombreusuario: 'Miss Lorena Zieme DVM',
      password: 'fbqgpvrj',
      agendaOnline: '4',
      ciudad: 'Spring Valley',
      duracionConsulta: '7'
    },
    {
      idSucursal: '15756477',
      rut: '175',
      nombre: 'Henrietta Fadel',
      apellido: 'Reichert',
      telefono: '23-539608-345796-9',
      email: 'Jermain_Kessler@gmail.com',
      direccion: '04475',
      nombreusuario: 'Leslie Harber II',
      password: 'uzwgwvze',
      agendaOnline: '8',
      ciudad: 'Lansing',
      duracionConsulta: '8'
    },
    {
      idSucursal: '98002480',
      rut: '216',
      nombre: 'Mr. Orville Huel',
      apellido: 'Yundt',
      telefono: '51-430801-057449-5',
      email: 'Louvenia.Nader@yahoo.com',
      direccion: '55177',
      nombreusuario: 'Kelly Wunsch',
      password: 'ozkupvgy',
      agendaOnline: '1',
      ciudad: 'Denton',
      duracionConsulta: '0'
    },
    {
      idSucursal: '54230990',
      rut: '474',
      nombre: 'William Lebsack II',
      apellido: 'Bergstrom',
      telefono: '63-208144-093898-9',
      email: 'Darren63@yahoo.com',
      direccion: '727',
      nombreusuario: 'Leah Beer',
      password: 'xfekidqm',
      agendaOnline: '7',
      ciudad: 'Modesto',
      duracionConsulta: '3'
    },
    {
      idSucursal: '25470863',
      rut: '682',
      nombre: 'Lynette Quigley',
      apellido: 'Jast',
      telefono: '61-185466-473401-0',
      email: 'Benton.Cronin0@gmail.com',
      direccion: '29497',
      nombreusuario: 'Isabel Halvorson',
      password: 'dlgfdfwb',
      agendaOnline: '2',
      ciudad: 'Noblesville',
      duracionConsulta: '6'
    },
    {
        idSucursal: '69069442',
        rut: '686',
        nombre: 'Silvia Rosenbaum',
        apellido: 'Towne',
        telefono: '78-623398-544738-9',
        email: 'Drake.Russel18@yahoo.com',
        direccion: '6625',
        nombreusuario: 'Lela Klein',
        password: 'enwxsrbu',
        agendaOnline: '9',
        ciudad: 'Daly City',
        duracionConsulta: '8'
      },
      {
        idSucursal: '21013794',
        rut: '088',
        nombre: 'Laurence Powlowski',
        apellido: 'McGlynn',
        telefono: '72-971446-020356-1',
        email: 'Charley.Davis26@gmail.com',
        direccion: '1097',
        nombreusuario: 'Andres Wiegand',
        password: 'kciqtzoi',
        agendaOnline: '8',
        ciudad: 'Conway',
        duracionConsulta: '1'
      },
      {
        idSucursal: '69301369',
        rut: '816',
        nombre: 'Wallace Yost',
        apellido: 'Jenkins',
        telefono: '29-159739-034054-8',
        email: 'Elody.Gutkowski@yahoo.com',
        direccion: '0862',
        nombreusuario: 'Emmett Rippin',
        password: 'clitxciu',
        agendaOnline: '7',
        ciudad: 'Diamond Bar',
        duracionConsulta: '6'
      },
      {
        idSucursal: '37256983',
        rut: '711',
        nombre: 'Glenda Blick',
        apellido: 'Braun',
        telefono: '94-519030-629718-2',
        email: 'Adah.Boyer@gmail.com',
        direccion: '85246',
        nombreusuario: 'Luis Skiles',
        password: 'kejdlcjr',
        agendaOnline: '3',
        ciudad: 'Apex',
        duracionConsulta: '2'
      },
      {
        idSucursal: '35183070',
        rut: '578',
        nombre: 'Sophia Senger',
        apellido: 'Gottlieb',
        telefono: '50-672691-027610-3',
        email: 'Ronny_Bogisich@gmail.com',
        direccion: '35093',
        nombreusuario: 'Vivian Torphy DDS',
        password: 'iyekuqup',
        agendaOnline: '1',
        ciudad: 'Yucaipa',
        duracionConsulta: '9'
      },
      {
        idSucursal: '16547728',
        rut: '632',
        nombre: 'Miss Josefina Fisher',
        apellido: 'Kunze',
        telefono: '56-104776-666168-2',
        email: 'Quentin72@gmail.com',
        direccion: '27728',
        nombreusuario: 'Kari Kirlin',
        password: 'mtapkoff',
        agendaOnline: '3',
        ciudad: 'Cuyahoga Falls',
        duracionConsulta: '9'
      },
      {
        idSucursal: '56813843',
        rut: '764',
        nombre: "Peggy D'Amore V",
        apellido: 'Dare',
        telefono: '45-299231-606569-8',
        email: 'Hollis.Gottlieb@yahoo.com',
        direccion: '7168',
        nombreusuario: 'Margarita Hickle',
        password: 'pjtgspdn',
        agendaOnline: '6',
        ciudad: 'Washington',
        duracionConsulta: '8'
      },
      {
        idSucursal: '43497796',
        rut: '821',
        nombre: 'Tracy Altenwerth',
        apellido: 'Brekke',
        telefono: '70-260503-518392-7',
        email: 'Prince15@hotmail.com',
        direccion: '18001',
        nombreusuario: 'Jeanette Heaney',
        password: 'hfliqyzh',
        agendaOnline: '6',
        ciudad: 'North Port',
        duracionConsulta: '5'
      },
      {
        idSucursal: '70810919',
        rut: '270',
        nombre: 'Brendan Powlowski',
        apellido: 'Batz',
        telefono: '85-867308-235919-8',
        email: 'Madalyn93@yahoo.com',
        direccion: '0032',
        nombreusuario: 'Norma Ortiz',
        password: 'dzmvwuoa',
        agendaOnline: '3',
        ciudad: 'San Rafael',
        duracionConsulta: '8'
      },
      {
        idSucursal: '47817683',
        rut: '296',
        nombre: 'Priscilla Braun V',
        apellido: 'Cummerata',
        telefono: '39-010744-708263-8',
        email: 'Mandy.Koch71@hotmail.com',
        direccion: '06754',
        nombreusuario: 'Alma Beier III',
        password: 'qoalcrvt',
        agendaOnline: '1',
        ciudad: 'Conroe',
        duracionConsulta: '7'
      },
      {
        idSucursal: '68353973',
        rut: '303',
        nombre: 'Nathan Kunze V',
        apellido: 'Hessel',
        telefono: '57-254921-121253-9',
        email: 'Ahmed.Kuhic48@hotmail.com',
        direccion: '0819',
        nombreusuario: 'Jared Bernier',
        password: 'ukzejgkf',
        agendaOnline: '3',
        ciudad: 'Madison',
        duracionConsulta: '5'
      },
      {
        idSucursal: '13507382',
        rut: '537',
        nombre: 'Rogelio Crona',
        apellido: 'Batz',
        telefono: '92-972032-956474-5',
        email: 'Devon13@hotmail.com',
        direccion: '38844',
        nombreusuario: 'Rachel Rodriguez',
        password: 'waqhnomf',
        agendaOnline: '4',
        ciudad: 'Oshkosh',
        duracionConsulta: '1'
      },
      {
        idSucursal: '12006830',
        rut: '585',
        nombre: 'Al Littel',
        apellido: 'Sipes',
        telefono: '95-643047-770999-5',
        email: 'Franz.Medhurst@gmail.com',
        direccion: '7515',
        nombreusuario: 'Judy Schuster',
        password: 'mfwirfzd',
        agendaOnline: '9',
        ciudad: 'Vineland',
        duracionConsulta: '4'
      },
      {
        idSucursal: '40066203',
        rut: '266',
        nombre: 'Miss Norman Harber',
        apellido: 'Douglas',
        telefono: '58-565652-836082-1',
        email: 'Freddy.Kris@hotmail.com',
        direccion: '703',
        nombreusuario: 'Jacquelyn Wuckert',
        password: 'alijntfq',
        agendaOnline: '5',
        ciudad: 'Shreveport',
        duracionConsulta: '2'
      },
      {
        idSucursal: '08553861',
        rut: '649',
        nombre: 'Jeanette Feest',
        apellido: 'Powlowski',
        telefono: '62-174628-348359-9',
        email: 'Mervin_Emmerich@yahoo.com',
        direccion: '85441',
        nombreusuario: 'Arthur Stracke',
        password: 'haexqnzf',
        agendaOnline: '1',
        ciudad: 'Novi',
        duracionConsulta: '2'
      },
      {
        idSucursal: '61399767',
        rut: '447',
        nombre: 'Jacob Ratke',
        apellido: 'Hyatt',
        telefono: '42-704989-637261-4',
        email: 'Haylie_Nader@yahoo.com',
        direccion: '46663',
        nombreusuario: 'Cameron Brown',
        password: 'hjqkbgkw',
        agendaOnline: '6',
        ciudad: 'Jersey City',
        duracionConsulta: '5'
      },
      {
        idSucursal: '22675528',
        rut: '161',
        nombre: 'Devin Spencer',
        apellido: 'Wisoky',
        telefono: '07-413170-172532-1',
        email: 'Raymond.Harris81@yahoo.com',
        direccion: '48108',
        nombreusuario: 'Shane Franecki',
        password: 'xrzwysgv',
        agendaOnline: '3',
        ciudad: 'Fond du Lac',
        duracionConsulta: '8'
      },
      {
        idSucursal: '16302985',
        rut: '431',
        nombre: 'Joann Armstrong',
        apellido: 'Fritsch',
        telefono: '46-497639-994654-0',
        email: 'Werner.Kunze@yahoo.com',
        direccion: '5060',
        nombreusuario: 'Miss Brent Kozey',
        password: 'lwxysivu',
        agendaOnline: '9',
        ciudad: 'Hanford',
        duracionConsulta: '6'
      },
      {
        idSucursal: '06909596',
        rut: '218',
        nombre: 'Alexandra Harris',
        apellido: 'Runolfsson',
        telefono: '93-656308-362850-9',
        email: 'Rick.Littel0@yahoo.com',
        direccion: '51435',
        nombreusuario: 'Cory Hettinger',
        password: 'coamhofs',
        agendaOnline: '5',
        ciudad: 'Malden',
        duracionConsulta: '9'
      },
      {
        idSucursal: '94438112',
        rut: '040',
        nombre: 'Bethany Cartwright',
        apellido: 'Hermann',
        telefono: '61-556562-769448-1',
        email: 'Vern.Schimmel@gmail.com',
        direccion: '886',
        nombreusuario: 'Loretta Mayer',
        password: 'jzvvvvis',
        agendaOnline: '2',
        ciudad: 'Doral',
        duracionConsulta: '3'
      },
      {
        idSucursal: '10569464',
        rut: '424',
        nombre: 'Andres Bauch',
        apellido: 'Pollich',
        telefono: '87-517754-491142-1',
        email: 'Macey_Feeney@gmail.com',
        direccion: '64858',
        nombreusuario: 'Andrea Borer',
        password: 'tbywlwre',
        agendaOnline: '4',
        ciudad: 'Encinitas',
        duracionConsulta: '3'
      },
      {
        idSucursal: '77014698',
        rut: '307',
        nombre: 'Raul Treutel',
        apellido: 'Farrell',
        telefono: '01-977876-956889-0',
        email: 'Ewell_Rath@yahoo.com',
        direccion: '3030',
        nombreusuario: 'Craig Lind',
        password: 'abgrhakh',
        agendaOnline: '5',
        ciudad: 'Gaithersburg',
        duracionConsulta: '7'
      },
      {
        idSucursal: '81241950',
        rut: '120',
        nombre: 'Ms. Cameron Reilly',
        apellido: 'Kilback',
        telefono: '07-625785-040737-5',
        email: 'Tre88@hotmail.com',
        direccion: '0415',
        nombreusuario: 'Mr. Tricia Kilback',
        password: 'jxomfjwm',
        agendaOnline: '5',
        ciudad: 'Kingsport',
        duracionConsulta: '4'
      },
      {
        idSucursal: '81940268',
        rut: '051',
        nombre: 'Willie Corwin',
        apellido: 'Doyle',
        telefono: '47-596428-909214-3',
        email: 'Christina.Collier@hotmail.com',
        direccion: '21023',
        nombreusuario: 'Kelley Kub',
        password: 'zolcmzmv',
        agendaOnline: '1',
        ciudad: 'Pearland',
        duracionConsulta: '5'
      },
      {
        idSucursal: '52235148',
        rut: '204',
        nombre: 'Ms. Jessie Considine',
        apellido: 'Rau',
        telefono: '78-368708-572690-6',
        email: 'Serenity_Koelpin@yahoo.com',
        direccion: '680',
        nombreusuario: 'Clara Schaefer',
        password: 'itvwdikj',
        agendaOnline: '2',
        ciudad: 'DeKalb',
        duracionConsulta: '4'
      },
      {
        idSucursal: '83512266',
        rut: '282',
        nombre: 'May Rowe DVM',
        apellido: 'Bernhard',
        telefono: '54-938730-353426-6',
        email: 'Mckenzie.Bauch@hotmail.com',
        direccion: '8612',
        nombreusuario: 'Miss Pamela Lockman',
        password: 'xvsfhrqy',
        agendaOnline: '3',
        ciudad: 'Doral',
        duracionConsulta: '4'
      },
      {
        idSucursal: '43596100',
        rut: '666',
        nombre: 'Erma Treutel',
        apellido: 'Langosh',
        telefono: '25-490431-853548-7',
        email: 'Eugene90@yahoo.com',
        direccion: '57110',
        nombreusuario: 'Mae Orn',
        password: 'sqvpssjy',
        agendaOnline: '4',
        ciudad: 'Orange',
        duracionConsulta: '5'
      },
      {
        idSucursal: '89225135',
        rut: '316',
        nombre: 'Camille Keeling',
        apellido: 'Fahey',
        telefono: '27-965501-032627-5',
        email: 'Gideon_Lowe60@hotmail.com',
        direccion: '5378',
        nombreusuario: 'Emmett Reilly',
        password: 'xcbcndji',
        agendaOnline: '5',
        ciudad: 'Greenwood',
        duracionConsulta: '8'
      },
      {
        idSucursal: '95336238',
        rut: '806',
        nombre: 'Candice Langosh',
        apellido: 'Cruickshank',
        telefono: '92-092877-496030-5',
        email: 'Hazel_Schowalter@gmail.com',
        direccion: '017',
        nombreusuario: 'Christopher Renner',
        password: 'wdgzkazz',
        agendaOnline: '8',
        ciudad: 'Valdosta',
        duracionConsulta: '8'
      },
      {
        idSucursal: '72609512',
        rut: '022',
        nombre: "Lena O'Keefe",
        apellido: 'Cole',
        telefono: '71-902739-129961-2',
        email: 'Kody.Hartmann14@gmail.com',
        direccion: '3166',
        nombreusuario: 'Rene Nicolas',
        password: 'gsladtlz',
        agendaOnline: '4',
        ciudad: 'Melbourne',
        duracionConsulta: '4'
      },
      {
        idSucursal: '98393109',
        rut: '876',
        nombre: 'Delia Altenwerth',
        apellido: 'Halvorson',
        telefono: '62-980724-894246-7',
        email: 'Kurt.Hayes23@gmail.com',
        direccion: '293',
        nombreusuario: 'Winston Effertz',
        password: 'jcjqjsty',
        agendaOnline: '5',
        ciudad: 'Fort Wayne',
        duracionConsulta: '7'
      },
      {
        idSucursal: '02867234',
        rut: '085',
        nombre: 'Dwight Stehr',
        apellido: 'Volkman',
        telefono: '40-886683-053316-4',
        email: 'Antoinette_Haag90@yahoo.com',
        direccion: '4707',
        nombreusuario: 'Kent Kessler',
        password: 'tqwathts',
        agendaOnline: '2',
        ciudad: 'Royal Oak',
        duracionConsulta: '9'
      },
      {
        idSucursal: '13156385',
        rut: '793',
        nombre: 'Rosemarie Fay',
        apellido: 'Bahringer',
        telefono: '72-431500-533147-2',
        email: 'Lester_Daniel@gmail.com',
        direccion: '310',
        nombreusuario: 'Van Harber',
        password: 'eitmynel',
        agendaOnline: '8',
        ciudad: 'Coral Springs',
        duracionConsulta: '0'
      },
      {
        idSucursal: '00929644',
        rut: '532',
        nombre: 'Tyrone Zieme',
        apellido: 'Kutch',
        telefono: '47-235982-434140-7',
        email: 'Marcus56@gmail.com',
        direccion: '066',
        nombreusuario: 'Elsa Skiles',
        password: 'aleehpuc',
        agendaOnline: '8',
        ciudad: 'Meridian',
        duracionConsulta: '3'
      },
      {
        idSucursal: '64508665',
        rut: '073',
        nombre: 'Mrs. Edmond Leuschke IV',
        apellido: 'Little',
        telefono: '13-216670-202759-0',
        email: 'Alta_Emmerich95@yahoo.com',
        direccion: '35689',
        nombreusuario: 'Edmund Deckow',
        password: 'psnqctol',
        agendaOnline: '8',
        ciudad: 'Fountainebleau',
        duracionConsulta: '2'
      },
      {
        idSucursal: '37020266',
        rut: '809',
        nombre: 'Bennie Gleason',
        apellido: 'Parker',
        telefono: '51-570419-883995-8',
        email: 'Jacinto.Weber37@gmail.com',
        direccion: '764',
        nombreusuario: 'Lana Lowe',
        password: 'iumpypjk',
        agendaOnline: '9',
        ciudad: 'Petaluma',
        duracionConsulta: '2'
      },
      {
        idSucursal: '81517247',
        rut: '780',
        nombre: 'Lowell Heaney',
        apellido: 'Davis',
        telefono: '72-620991-982296-5',
        email: 'Hank72@gmail.com',
        direccion: '098',
        nombreusuario: 'Megan Greenholt',
        password: 'tunidyru',
        agendaOnline: '6',
        ciudad: 'Orland Park',
        duracionConsulta: '9'
      },
      {
        idSucursal: '25404302',
        rut: '548',
        nombre: 'Faith Bartoletti',
        apellido: 'Ritchie',
        telefono: '25-653315-460454-1',
        email: 'Mohammed.Erdman85@hotmail.com',
        direccion: '5709',
        nombreusuario: 'Robert Cartwright',
        password: 'vfpdkicy',
        agendaOnline: '5',
        ciudad: 'Burlington',
        duracionConsulta: '4'
      },
      {
        idSucursal: '22802717',
        rut: '142',
        nombre: 'Travis Kuvalis',
        apellido: 'Cruickshank',
        telefono: '49-020945-973638-9',
        email: 'Sterling_Connelly81@hotmail.com',
        direccion: '075',
        nombreusuario: 'Jeffery Halvorson',
        password: 'nghhxkfs',
        agendaOnline: '1',
        ciudad: 'Fullerton',
        duracionConsulta: '2'
      },
      {
        idSucursal: '55564033',
        rut: '754',
        nombre: 'Mr. Ricardo Huels',
        apellido: 'Ward',
        telefono: '02-443626-645854-4',
        email: 'Sherman20@gmail.com',
        direccion: '264',
        nombreusuario: 'Angelica Zemlak',
        password: 'tyzjtbfm',
        agendaOnline: '9',
        ciudad: 'Rancho Cucamonga',
        duracionConsulta: '1'
      },
      {
        idSucursal: '20666592',
        rut: '395',
        nombre: 'Irma Reilly',
        apellido: 'Schaefer',
        telefono: '29-655036-826406-2',
        email: 'Keven.Kunde18@hotmail.com',
        direccion: '0281',
        nombreusuario: 'Claude Price',
        password: 'xiwahqrp',
        agendaOnline: '7',
        ciudad: 'Vista',
        duracionConsulta: '3'
      },
      {
        idSucursal: '85532616',
        rut: '661',
        nombre: 'Nora Marquardt',
        apellido: 'Lakin',
        telefono: '72-689750-013795-7',
        email: 'Cathryn_Batz@hotmail.com',
        direccion: '3902',
        nombreusuario: 'Aaron Koelpin',
        password: 'qpnnwooe',
        agendaOnline: '9',
        ciudad: 'Blaine',
        duracionConsulta: '6'
      },
      {
        idSucursal: '63763342',
        rut: '056',
        nombre: 'Joanne Deckow',
        apellido: 'Bergstrom',
        telefono: '53-460749-583087-6',
        email: 'Laurianne18@gmail.com',
        direccion: '66548',
        nombreusuario: 'Lorraine Hoppe',
        password: 'tybazhrh',
        agendaOnline: '5',
        ciudad: 'Smyrna',
        duracionConsulta: '7'
      },
      {
        idSucursal: '35006277',
        rut: '869',
        nombre: 'Ms. Maryann Krajcik',
        apellido: "O'Reilly",
        telefono: '51-066992-366260-0',
        email: 'Kennedy_Wintheiser41@hotmail.com',
        direccion: '24654',
        nombreusuario: 'Luis Pfeffer V',
        password: 'mignyxyf',
        agendaOnline: '8',
        ciudad: 'Syracuse',
        duracionConsulta: '4'
      },
      {
        idSucursal: '71051359',
        rut: '900',
        nombre: 'Morris Reynolds',
        apellido: 'Mills',
        telefono: '78-996706-991140-9',
        email: 'Aliza38@yahoo.com',
        direccion: '5505',
        nombreusuario: 'Gilbert Cormier',
        password: 'rzzkxjhy',
        agendaOnline: '4',
        ciudad: 'Temecula',
        duracionConsulta: '5'
      },
      {
        idSucursal: '87951823',
        rut: '766',
        nombre: 'Ms. Terrance Daugherty',
        apellido: 'Hegmann',
        telefono: '06-661887-912926-0',
        email: 'Ida89@gmail.com',
        direccion: '4416',
        nombreusuario: 'Cathy Ryan',
        password: 'ykvzixmb',
        agendaOnline: '4',
        ciudad: 'Memphis',
        duracionConsulta: '8'
      },
      {
        idSucursal: '30415275',
        rut: '478',
        nombre: 'Patricia Lowe',
        apellido: 'Kemmer',
        telefono: '73-981487-916091-1',
        email: 'Lemuel72@yahoo.com',
        direccion: '6290',
        nombreusuario: "Ashley O'Hara",
        password: 'gskvxwtl',
        agendaOnline: '1',
        ciudad: 'Wylie',
        duracionConsulta: '3'
      },
      {
        idSucursal: '15398352',
        rut: '518',
        nombre: 'Marguerite Walsh',
        apellido: 'Bode',
        telefono: '92-637872-644082-0',
        email: 'Kamren93@yahoo.com',
        direccion: '574',
        nombreusuario: 'Cedric Armstrong',
        password: 'uyptbpzk',
        agendaOnline: '1',
        ciudad: 'Clifton',
        duracionConsulta: '4'
      },
      {
        idSucursal: '68929765',
        rut: '173',
        nombre: 'Lucy Reilly',
        apellido: 'Runolfsson',
        telefono: '27-487854-120589-2',
        email: 'Romaine64@yahoo.com',
        direccion: '485',
        nombreusuario: 'Jack Howell',
        password: 'cwszmzft',
        agendaOnline: '8',
        ciudad: 'San Jacinto',
        duracionConsulta: '2'
      },
      {
        idSucursal: '15530800',
        rut: '807',
        nombre: 'Lance Dicki IV',
        apellido: 'Gutmann',
        telefono: '38-688115-386821-8',
        email: 'Maia.Reilly@hotmail.com',
        direccion: '65445',
        nombreusuario: 'Sandy Dooley',
        password: 'lvzmamih',
        agendaOnline: '1',
        ciudad: 'Lakeville',
        duracionConsulta: '2'
      },
      {
        idSucursal: '58752049',
        rut: '618',
        nombre: 'Winston Zboncak II',
        apellido: 'Spinka',
        telefono: '06-786179-466061-8',
        email: 'Jennifer42@yahoo.com',
        direccion: '658',
        nombreusuario: 'Molly Barton',
        password: 'cocdzghb',
        agendaOnline: '7',
        ciudad: 'Bakersfield',
        duracionConsulta: '4'
      },
      {
        idSucursal: '09111911',
        rut: '633',
        nombre: 'Albert Kuhlman',
        apellido: 'Will',
        telefono: '15-645894-136276-8',
        email: 'Tanya_Rutherford62@hotmail.com',
        direccion: '55665',
        nombreusuario: 'Troy Ebert I',
        password: 'rerarmwr',
        agendaOnline: '9',
        ciudad: 'Lehigh Acres',
        duracionConsulta: '4'
      },
      {
        idSucursal: '50734273',
        rut: '038',
        nombre: 'Rex Kunze',
        apellido: 'Windler',
        telefono: '40-684815-073713-0',
        email: 'Timothy16@hotmail.com',
        direccion: '44792',
        nombreusuario: 'Rickey Stiedemann',
        password: 'imukcdpp',
        agendaOnline: '4',
        ciudad: 'Bozeman',
        duracionConsulta: '3'
      },
      {
        idSucursal: '55516587',
        rut: '008',
        nombre: 'Miss Gustavo Sauer',
        apellido: 'Herzog',
        telefono: '43-379693-983279-6',
        email: 'Keven_Keebler@hotmail.com',
        direccion: '713',
        nombreusuario: 'Dr. Anna Raynor',
        password: 'cyyqriln',
        agendaOnline: '6',
        ciudad: 'West Seneca',
        duracionConsulta: '4'
      },
      {
        idSucursal: '84548924',
        rut: '560',
        nombre: 'Dolores Swaniawski',
        apellido: 'Leffler',
        telefono: '47-264672-225583-2',
        email: 'Fabian.Robel@yahoo.com',
        direccion: '34287',
        nombreusuario: 'Naomi Schamberger',
        password: 'jkptczyv',
        agendaOnline: '3',
        ciudad: 'Dunwoody',
        duracionConsulta: '6'
      },
      {
        idSucursal: '89873165',
        rut: '583',
        nombre: 'Mr. Naomi Boehm',
        apellido: 'Ondricka',
        telefono: '75-582418-058346-0',
        email: 'Rodger.Beer@yahoo.com',
        direccion: '59346',
        nombreusuario: 'Margie Conroy',
        password: 'xwcqtfsg',
        agendaOnline: '5',
        ciudad: 'Sterling Heights',
        duracionConsulta: '1'
      },
      {
        idSucursal: '68304753',
        rut: '735',
        nombre: 'Jesus Reinger',
        apellido: 'McCullough',
        telefono: '37-148277-369945-0',
        email: 'Riley.Schuster20@hotmail.com',
        direccion: '2799',
        nombreusuario: 'Miss Josephine Sanford',
        password: 'mzlxhelj',
        agendaOnline: '9',
        ciudad: 'Lake Charles',
        duracionConsulta: '5'
      },
      {
        idSucursal: '16298003',
        rut: '504',
        nombre: 'Lela Ortiz',
        apellido: 'Raynor',
        telefono: '06-001971-285500-3',
        email: 'Korey_Krajcik@yahoo.com',
        direccion: '842',
        nombreusuario: 'Dewey Olson',
        password: 'ncdyonub',
        agendaOnline: '2',
        ciudad: 'Lafayette',
        duracionConsulta: '7'
      },
      {
        idSucursal: '63796168',
        rut: '914',
        nombre: 'Diana Nitzsche',
        apellido: 'Weimann',
        telefono: '24-234311-226552-7',
        email: 'Margot.Harris@hotmail.com',
        direccion: '0119',
        nombreusuario: 'Erma Paucek',
        password: 'cdlihzgl',
        agendaOnline: '1',
        ciudad: 'Battle Creek',
        duracionConsulta: '2'
      },
      {
        idSucursal: '46897999',
        rut: '563',
        nombre: 'Vicki Gerlach',
        apellido: 'Schuppe',
        telefono: '69-863419-657886-1',
        email: 'Camden.Wunsch@gmail.com',
        direccion: '70981',
        nombreusuario: 'Benny Buckridge',
        password: 'sisibpxe',
        agendaOnline: '9',
        ciudad: 'University',
        duracionConsulta: '4'
      },
      {
        idSucursal: '68210907',
        rut: '034',
        nombre: 'Steve Halvorson',
        apellido: 'Trantow',
        telefono: '86-767890-359372-6',
        email: 'Delmer8@gmail.com',
        direccion: '4062',
        nombreusuario: 'Tracy Wuckert',
        password: 'hwegdrjw',
        agendaOnline: '3',
        ciudad: 'Enterprise',
        duracionConsulta: '6'
      },
      {
        idSucursal: '61106608',
        rut: '566',
        nombre: 'Kayla Ondricka',
        apellido: 'Rice',
        telefono: '23-404632-727711-8',
        email: 'Rachel_Schoen41@gmail.com',
        direccion: '3484',
        nombreusuario: 'Rachel Fahey',
        password: 'mutywjsj',
        agendaOnline: '1',
        ciudad: 'Asheville',
        duracionConsulta: '4'
      },
      {
        idSucursal: '89794079',
        rut: '457',
        nombre: 'Heidi Witting',
        apellido: 'Feeney',
        telefono: '77-831383-875728-1',
        email: 'Marietta_Ankunding@hotmail.com',
        direccion: '1674',
        nombreusuario: 'Miss Herbert Hilll',
        password: 'yephbnkc',
        agendaOnline: '5',
        ciudad: 'Cathedral City',
        duracionConsulta: '0'
      },
      {
        idSucursal: '07290883',
        rut: '875',
        nombre: 'Roosevelt Greenholt',
        apellido: 'Sporer',
        telefono: '74-707784-055107-7',
        email: 'Charity_Weissnat@yahoo.com',
        direccion: '903',
        nombreusuario: 'Victor Wintheiser',
        password: 'hlfcludi',
        agendaOnline: '8',
        ciudad: 'Appleton',
        duracionConsulta: '6'
      },
      {
        idSucursal: '04469277',
        rut: '196',
        nombre: 'Claire McClure',
        apellido: 'Hirthe',
        telefono: '74-201068-771298-6',
        email: 'Madyson_Oberbrunner94@hotmail.com',
        direccion: '9277',
        nombreusuario: 'Wilma Kessler',
        password: 'whhejirj',
        agendaOnline: '5',
        ciudad: 'Lehigh Acres',
        duracionConsulta: '4'
      },
      {
        idSucursal: '57049315',
        rut: '408',
        nombre: 'Heidi Dach',
        apellido: 'Mann',
        telefono: '35-600266-032351-6',
        email: 'Dexter4@yahoo.com',
        direccion: '27415',
        nombreusuario: 'Leland Kirlin',
        password: 'exseypjp',
        agendaOnline: '3',
        ciudad: 'St. Louis Park',
        duracionConsulta: '2'
      },
      {
        idSucursal: '37732147',
        rut: '182',
        nombre: 'Vernon Dicki IV',
        apellido: 'Schroeder',
        telefono: '63-670358-502151-3',
        email: 'Kiara_Cronin@gmail.com',
        direccion: '4784',
        nombreusuario: 'Dawn Feeney',
        password: 'lehypzsy',
        agendaOnline: '7',
        ciudad: 'Manteca',
        duracionConsulta: '6'
      },
      {
        idSucursal: '16527692',
        rut: '217',
        nombre: 'Miss Marshall Davis',
        apellido: 'Batz',
        telefono: '36-129467-505671-9',
        email: 'Ray39@yahoo.com',
        direccion: '52979',
        nombreusuario: 'Jeremiah Harber',
        password: 'jumfdoey',
        agendaOnline: '2',
        ciudad: 'Port St. Lucie',
        duracionConsulta: '5'
      },
      {
        idSucursal: '44072985',
        rut: '852',
        nombre: 'Nick Collier',
        apellido: 'Nolan',
        telefono: '22-960288-632684-0',
        email: 'Barbara25@yahoo.com',
        direccion: '079',
        nombreusuario: 'Tracy Lockman',
        password: 'ehcgwsfp',
        agendaOnline: '8',
        ciudad: 'Johnson City',
        duracionConsulta: '4'
      },
      {
        idSucursal: '16250600',
        rut: '461',
        nombre: 'Freda McLaughlin',
        apellido: 'Casper',
        telefono: '93-393673-563603-4',
        email: 'Ines_Goldner@gmail.com',
        direccion: '914',
        nombreusuario: 'Jana Beier',
        password: 'mhkqkqvp',
        agendaOnline: '5',
        ciudad: 'Edinburg',
        duracionConsulta: '3'
      }
]